config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :items do
  	member do
  	  post :add_item_to_basket
  	end
  end
  resources :baskets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items, dependent: :destroy
  has_many :items, through: :basket_items

end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :basket
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :basket_items, dependent: :destroy
  has_many :baskets, through: :basket_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :basket
  after_create :build_basket

  private

  def build_basket
  	Basket.create(user_id: self.id)	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def admin?
  	return if current_user&.admin == true
  	redirect_to root_path
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!

  def show
  	if current_user.basket.id.to_s == params[:id] || current_user.admin == true
  	  @basket = Basket.find_by(id:params[:id])
  	else
  	  redirect_to root_path
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin?, only: [:edit, :update, :destroy]

  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)

  	if @item.save
  	  redirect_to item_path(@item)
  	else
  	  render :new
  	end
  end

  def show
  	@item = Item.find_by(id: params[:id])
  end

  def edit
  	@item = Item.find_by(id: params[:id])
  end

  def update
  	@item = Item.find_by(id: params[:id])

  	if @item.update(item_params)
  	  redirect_to item_path(@item)
  	else
  	  render :edit
  	end
  end

  def destroy
  	@item = Item.find_by(id: params[:id])
  	@item.destroy

  	if @item.destroyed?
  	  redirect_to items_path
  	else
      redirect_to item_path(@item)
  	end
  end

  def add_item_to_basket
    current_user.basket.items << Item.find_by(id: params[:id])
  	redirect_to basket_path(current_user.basket)
  end

  private

  def item_params
  	params.require(:item).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    return true if current_user&.admin == true
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/baskets/show.html.erb
<h1>Basket of user: <%= @basket.user.email %></h1>
<h3>Items of basket: </h3>
<% @basket.items.each do |item| %>
  <%= link_to item.name, item_path(item.id) %>
  <br>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_with model: @item, local:true do |f| %>
  <%= f.label "Name" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Description" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <%= f.submit "ok" %>
<% end %>

app/views/items/index.html.erb
<h1>All items</h1>
<%= link_to "create new item", new_item_path %>
<br>
<% @items.each do |item| %>
  <%= link_to item.name, item_path(item.id) %>
  <br>
<% end %>

app/views/items/new.html.erb
<h1>Create New item</h1>

<%= form_with model: @item, local:true do |f| %>
  <%= f.label "Name" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Description" %>
  <br>
  <%= f.text_area :description %>
  <br>
  <%= f.submit "ok" %>
<% end %>

app/views/items/show.html.erb
<h1>Item <%= @item.name %></h1>
<h5><%= @item.description %></h5>
<br>
<% if admin? %>
  <%= link_to "edit", edit_item_path(@item.id) %>
  <%= link_to "delete", item_path(@item.id), method: :delete %>
<% end %>
<%= link_to "add to basket", add_item_to_basket_item_path(@item.id), method: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="session_block">
      <% if signed_in? %>
        <%= current_user.email %>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "login", new_user_session_path %>
        <br>
        <%= link_to "sign up", new_user_registration_path %>
      <% end %>
    </div>
    <%= link_to "Items", items_path if signed_in? %>
    <%= link_to "my basket", basket_path(current_user.basket.id) if signed_in? %>
    <br>
    <%= yield %>
  </body>
</html>